#include <arm/smccc/psci.h>
#include <arm/smccc/smc.h>
#include <stdint.h>

#include "kernel/mm.h"
#include "kernel/panic.h"

// NOTE: generated by an LLM provided the arm documentation (Arm Power State
// Coordination Interface Platform Design Document Version 1.3 issue F.b)

// Power State Coordination Interface (PSCI), uses SMC64 when available
typedef enum {
    // Base
    PSCI_VERSION = 0x84000000u,

    // CPU control
    PSCI_CPU_SUSPEND = 0xC4000001u,
    PSCI_CPU_OFF     = 0x84000002u,
    PSCI_CPU_ON      = 0xC4000003u,

    // Affinity / topology
    PSCI_AFFINITY_INFO = 0xC4000004u,

    // Migration (optional)
    PSCI_MIGRATE             = 0xC4000005u,
    PSCI_MIGRATE_INFO_TYPE   = 0x84000006u,
    PSCI_MIGRATE_INFO_UP_CPU = 0xC4000007u,

    // System control
    PSCI_SYSTEM_OFF   = 0x84000008u,
    PSCI_SYSTEM_RESET = 0x84000009u,

    // PSCI >= 1.0
    PSCI_PSCI_FEATURES = 0x8400000Au,

    // PSCI >= 1.0 (power mgmt extensions)
    PSCI_CPU_FREEZE          = 0x8400000Bu,
    PSCI_CPU_DEFAULT_SUSPEND = 0xC400000Cu,
    PSCI_NODE_HW_STATE       = 0xC400000Du,
    PSCI_SYSTEM_SUSPEND      = 0xC400000Eu,

    // PSCI >= 1.0 stats
    PSCI_STAT_RESIDENCY = 0xC4000010u,
    PSCI_STAT_COUNT     = 0xC4000011u,

    // PSCI >= 1.1
    PSCI_SYSTEM_RESET2           = 0xC4000012u,
    PSCI_MEM_PROTECT             = 0xC4000013u,
    PSCI_MEM_PROTECT_CHECK_RANGE = 0xC4000014u,

    // PSCI >= 1.3
    PSCI_SYSTEM_OFF2 = 0xC4000015u,
} psci_fid;




noreturn void psci_cpu_off()
{
    smccc_res_t res = _smc_call(PSCI_CPU_OFF, 0, 0, 0, 0, 0, 0, 0);
    ASSERT((int32_t)res.x0 == PSCI_DENIED, "PSCI_CPU_OFF denied");
    PANIC();
}



psci_return_code psci_cpu_on(
    arm_cpu_affinity  target_cpu,
    psci_cpu_on_entry phys_entry_point_address,
    size_t            context_id // passed as x0 on the waken core
)
{
    ASSERT(!is_kva_ptr(phys_entry_point_address));

    uint64_t mpidr =
        ((uint64_t)target_cpu.aff3 << 32 | (uint64_t)target_cpu.aff2 << 16 |
         (uint64_t)target_cpu.aff1 << 8 | (uint64_t)target_cpu.aff0);

    smccc_res_t res = _smc_call(
        PSCI_CPU_ON,
        mpidr,
        (uint64_t)phys_entry_point_address,
        context_id,
        0,
        0,
        0,
        0);

    psci_return_code code = res.x0;

    ASSERT(
        code == PSCI_SUCCESS || code == PSCI_INVALID_PARAMETERS ||
        code == PSCI_INVALID_ADDRESS || code == PSCI_ALREADY_ON ||
        code == PSCI_ON_PENDING || code == PSCI_INTERNAL_FAILURE ||
        code == PSCI_DENIED);

    return code;
}


noreturn void psci_system_off()
{
    _smc_call(PSCI_SYSTEM_OFF, 0, 0, 0, 0, 0, 0, 0);

    __builtin_unreachable();
}